#!/bin/bash

echo Overwriting PDAEMON with insane buggy script, you are warned

old=0x$(nvapeek 200 | sed -e s@.*\ @@)

nvapoke 200 $(printf %x $(($old & ~(1<<13))))
nvapoke 200 $old

nvapoke 0x10a180 0x01000000
nvapoke 0x10a47c 0x7013452f

n=0
while read line; do
	if [ $(($n % 64)) -eq 0 ]; then
		nvapoke 0x10a188 $(printf %x $(($n >> 6)))
	fi

	n=$((${n}+1));
	nvapoke 0x10a184 $line;
done

while [ $(($n % 64)) -ne 0 ]; do
	nvapoke 0x10a184 0
	n=$((${n}+1))
done

nvapoke 0x10a1c0 0x01005500
for i in `seq 0 255`; do nvapoke 0x10a1c4 0; done

nvapoke 0x10a10c 0
nvapoke 0x10a104 0

echo Too late, uploading now

nvapoke 0x10a100 2

addr=55e0
len=40

nvapoke 0x10a1c0 0x0200${addr}

for n in `seq 0 $((0x${len}/4-1))`; do
printf "%x: %s\n" $((0x${addr} + $n * 4)) $(nvapeek 0x10a1c4 | sed -e s@.*\ @@)
done

